FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    # Tesseract OCR motoru + Türkçe dil paketi
    tesseract-ocr \
    tesseract-ocr-tur \
    tesseract-ocr-eng \
    # PDF ve görüntü işleme için system kütüphaneleri
    libmupdf-dev \
    mupdf-tools \
    poppler-utils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir --default-timeout=100 -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]